apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-env
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/abhradippaul/DevOps.git
    targetRevision: HEAD
    path: manifests/kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true